/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Ant: typeof import('./src/components/Ant.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    Element: typeof import('./src/components/Element.vue')['default']
    Vant: typeof import('./src/components/Vant.vue')['default']
    ViewDesigin: typeof import('./src/components/ViewDesigin.vue')['default']
  }
}
